group: stable
sudo: false
language: ruby
addons:
  postgresql: '9.3'
  apt:
    packages:
      - graphviz
rvm:
  - 2.6.5
before_install:
  - gem install bundler
script:
  - bundle exec rake spec
  - bundle exec rake cucumber
  - bundle exec rake yard
